version: "3.5"

services:
    webserver:
      image: nginx:alpine
      container_name: php-webserver
      volumes:
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./:/application
      ports:
       - "8080:80"
      depends_on:
       - php-fpm
       - db

    php-fpm:
      image: php-fpm
      build:
        context: .
        dockerfile: docker/php-fpm/Dockerfile${DOCKER_ENVIRONMENT}
        args:
          - LOCAL_UID=${LOCAL_UID}
          - LOCAL_GID=${LOCAL_GID}
      container_name: php-fpm
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/infrastructure-overrides.ini
        - ./var:/application/var
      environment:
        XDEBUG_CONFIG: remote_host=${XDEBUG_REMOTE_HOST} remote_enable=${XDEBUG_REMOTE_ENABLE}
        PHP_IDE_CONFIG: serverName=${XDEBUG_SERVER_NAME}
        BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
        BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}
        BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
        BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}

    php-cron:
      container_name: php-cron
      build:
        context: .
        dockerfile: ./docker/jobs/Dockerfile
      depends_on:
        - php-fpm
      volumes:
        - ./:/application

    db:
      container_name: php-mongo
      image: mongo:4.0
      volumes:
        - db-data:/data/db:rw

volumes:
  db-data: { }
